// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Obtiene una lista paginada de usuarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Listar usuarios",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": " ",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": " ",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.PaginatedUsersResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo usuario en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Crear usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_eren_dev_go_server_internal_shared_validation.ValidationError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Obtiene un usuario por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Obtener usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.UserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un usuario por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Eliminar usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza un usuario existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Actualizar usuario",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.UpdateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_modules_users.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_eren_dev_go_server_internal_shared_validation.ValidationError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_eren_dev_go_server_internal_shared_pagination.PaginationInfo": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Límite de registros por página",
                    "type": "integer",
                    "example": 10
                },
                "skip": {
                    "description": "Registros saltados",
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "description": "Total de registros",
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "description": "Total de páginas",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "github_com_eren_dev_go_server_internal_shared_validation.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "Nombre del campo con error",
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "description": "Mensaje de error",
                    "type": "string",
                    "example": "must be a valid email"
                }
            }
        },
        "github_com_eren_dev_go_server_internal_shared_validation.ValidationError": {
            "type": "object",
            "properties": {
                "errors": {
                    "description": "Lista de errores por campo",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_eren_dev_go_server_internal_shared_validation.FieldError"
                    }
                }
            }
        },
        "internal_modules_users.CreateUserDTO": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "description": "Email del usuario",
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "description": "Nombre del usuario",
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "internal_modules_users.PaginatedUsersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Lista de usuarios",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_modules_users.UserResponse"
                    }
                },
                "pagination": {
                    "description": "Información de paginación",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_eren_dev_go_server_internal_shared_pagination.PaginationInfo"
                        }
                    ]
                }
            }
        },
        "internal_modules_users.UpdateUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Email del usuario",
                    "type": "string",
                    "example": "jane@example.com"
                },
                "name": {
                    "description": "Nombre del usuario",
                    "type": "string",
                    "example": "Jane Doe"
                }
            }
        },
        "internal_modules_users.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Fecha de creación",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "email": {
                    "description": "Email del usuario",
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "description": "ID único del usuario",
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "name": {
                    "description": "Nombre del usuario",
                    "type": "string",
                    "example": "John Doe"
                },
                "updated_at": {
                    "description": "Fecha de actualización",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Ingresa el token con el prefijo Bearer: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go Server API",
	Description:      "Template API con Go + Gin + MongoDB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
